### ISSUE TITLE
A BUG

### ISSUE THREAD

**Issue by cylindrical2002** [guangyliu/LatentOps#2] opened 2022-11-01 13:17 UTC
We followed your Readme.md, but I found this problem:

11/01/2022 21:15:14 - INFO - __main__ -   Pre-trained Optimus is successfully loaded
Traceback (most recent call last):
  File "examples/big_ae/conditional_generation.py", line 511, in <module>
    main()
  File "examples/big_ae/conditional_generation.py", line 458, in main
    model_vae.to(args.device)  #
  File "/home/ubuntu/anaconda3/envs/RL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/home/ubuntu/anaconda3/envs/RL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/home/ubuntu/anaconda3/envs/RL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/home/ubuntu/anaconda3/envs/RL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/home/ubuntu/anaconda3/envs/RL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/home/ubuntu/anaconda3/envs/RL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: unknown error

Do you know how to fix it ???

**Comment by guangyliu** [comment] 2022-11-01 15:55
Hi, what type of GPU is on your server? It seems the problem about the GPU.

**Comment by guangyliu** [comment] 2022-11-04 05:55
If the problem is solved, I will close this issue later.

**Closed as completed** 2022-11-05 10:12 UTC
